// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(app, express, passport) {
    var router;
    router = express.Router();
    router.get('/', function(req, res, next) {
      return res.render('home', {
        title: 'Enterprise Dual Strategy'
      });
    });
    router.get('messenger', function(req, res, next) {
      return res.render('index', {
        title: 'Enterprise Dual Strategy'
      });
    });
    app.use('/', router);
    require('./messenger')(app, express, passport);
    require('./session')(app, express, passport);
    return require('./user')(app, express, passport);
  };

}).call(this);

//# sourceMappingURL=index.map
