// Generated by CoffeeScript 1.7.1
(function() {
  var Merchant, User;

  User = require('../models/user');

  Merchant = require('../models/merchant');

  module.exports = function(app, express, passport) {
    var router;
    router = express.Router();
    router.get('/', function(req, res, next) {
      return res.render('home', {
        title: 'Enterprise Dual Strategy'
      });
    });
    router.get('/merc', function(req, res) {
      var merc;
      merc = new Merchant();
      merc.name = 'Huỳnh Châu';
      return merc.save(function(error) {
        if (error) {
          throw error;
        }
        return res.send(merc);
      });
    });
    router.get('/login', function(req, res, next) {
      if (req.isAuthenticated()) {
        res.redirect('/');
      }
      return res.render('login', {
        message: req.flash('loginMessage')
      });
    });
    router.post('/login', passport.authenticate('local-login', {
      successRedirect: '/',
      failureRedirect: '/login',
      failureFlash: true
    }));
    router.get('/logout', function(req, res) {
      req.logout();
      return res.redirect('/login');
    });
    router.get('/signup', function(req, res, next) {
      console.log(req.isAuthenticated());
      if (req.isAuthenticated()) {
        res.redirect('/');
      }
      return res.render('signup', {
        message: req.flash('signupMessage')
      });
    });
    router.post('/signup', passport.authenticate('local-signup', {
      successRedirect: '/',
      failureRedirect: '/signup',
      failureFlash: true
    }));
    router.get('messenger', function(req, res, next) {
      return res.render('index', {
        title: 'Enterprise Dual Strategy'
      });
    });
    app.use('/', router);
    require('./messenger')(app, express, passport);
    require('./session')(app, express, passport);
    return require('./user')(app, express, passport);
  };

}).call(this);

//# sourceMappingURL=index.map
