// Generated by CoffeeScript 1.7.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  module.exports = router;

}).call(this);

//# sourceMappingURL=messenger.map
