// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(app, express, passport) {
    var messenger;
    messenger = express.Router();
    return app.use('/messenger', messenger);
  };

}).call(this);

//# sourceMappingURL=messenger.map
