// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(app, express, passport) {
    var session;
    session = express.Router();
    session.get('/', function(req, res, next) {
      return res.render('login');
    });
    session.post('/', passport.authenticate('local-login', {
      successRedirect: '/test',
      failureRedirect: '/session',
      failureFlash: true
    }));
    session.get('/signup', function(req, res, next) {
      return res.render('signup', {
        message: req.flash('signupMessage')
      });
    });
    session.post('/signup', passport.authenticate('local-signup', {
      successRedirect: '/',
      failureRedirect: '/session/signup',
      failureFlash: true
    }));
    return app.use('/session', session);
  };

}).call(this);

//# sourceMappingURL=session.map
