// Generated by CoffeeScript 1.7.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res) {
    return res.render('login');
  });

  router.post('/create', function(req, res) {
    return res.send(req.body);
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=session.map
